import { approveProposalToolDef as approveProposalToolDefImpl } from "./approve-proposal";
import { completeOnboardingToolDef as completeOnboardingToolDefImpl } from "./complete-onboarding";
import { connectEvidenceSourceToolDef as connectEvidenceSourceToolDefImpl } from "./connect-evidence-source";
import { configureWebhookToolDef as configureWebhookToolDefImpl } from "./configure-webhook";
import { createBotToolDef as createBotToolDefImpl } from "./create-bot";
import { createSwarmToolDef as createSwarmToolDefImpl } from "./create-swarm";
import { docStatusToolDef as docStatusToolDefImpl } from "./doc-status";
import { editSystemPromptToolDef as editSystemPromptToolDefImpl } from "./edit-system-prompt";
import { generateDocsToolDef as generateDocsToolDefImpl } from "./generate-docs";
import { inspectControlGapsToolDef as inspectControlGapsToolDefImpl } from "./inspect-control-gaps";
import { resolveControlGapToolDef as resolveControlGapToolDefImpl } from "./resolve-control-gap";
import { syncEvidenceSourceToolDef as syncEvidenceSourceToolDefImpl } from "./sync-evidence-source";

export const approveProposalToolDef = approveProposalToolDefImpl;
export const completeOnboardingToolDef = completeOnboardingToolDefImpl;
export const connectEvidenceSourceToolDef = connectEvidenceSourceToolDefImpl;
export const configureWebhookToolDef = configureWebhookToolDefImpl;
export const createBotToolDef = createBotToolDefImpl;
export const createSwarmToolDef = createSwarmToolDefImpl;
export const docStatusToolDef = docStatusToolDefImpl;
export const editSystemPromptToolDef = editSystemPromptToolDefImpl;
export const generateDocsToolDef = generateDocsToolDefImpl;
export const inspectControlGapsToolDef = inspectControlGapsToolDefImpl;
export const resolveControlGapToolDef = resolveControlGapToolDefImpl;
export const syncEvidenceSourceToolDef = syncEvidenceSourceToolDefImpl;
