import type { BotDefinition, BotFinding } from "./types";
import type { Nanobot, NanobotContext, NanobotResult } from "../types";
import { executeBot, type RepoFile as EngineRepoFile } from "./engine";
import { getModel } from "@/lib/llm/provider";

/**
 * Adapt a BotDefinition to the SaaS Nanobot interface.
 * This bridges the new data-driven bot system with the existing orchestrator.
 */
export function adaptToNanobot(bot: BotDefinition): Nanobot {
  const category = bot.category === "docs" ? "docs" : "security";

  return {
    name: bot.name,
    description: bot.description,
    category: category as "security" | "docs",
    fileExtensions: bot.config.fileExtensions ?? [],

    async run(ctx: NanobotContext): Promise<NanobotResult | null> {
      const model = getModel();

      // Merge context system prompt if provided
      const effectiveBot: BotDefinition = ctx.systemPrompt
        ? { ...bot, systemPrompt: ctx.systemPrompt }
        : bot;

      const files: EngineRepoFile[] = ctx.files.map((f) => ({
        path: f.path,
        content: f.content,
      }));

      const findings = await executeBot(effectiveBot, files, model, ctx.onEvent);

      if (findings.length === 0) return null;

      // Separate findings into file changes and informational
      const changedFiles = findings
        .filter((f) => f.fixedContent)
        .map((f) => ({ path: f.file, content: f.fixedContent! }));

      return {
        nanobot: bot.name,
        changedFiles,
        deletedFiles: [],
        prTitle: buildPrTitle(bot, findings),
        prBody: buildPrBody(bot, findings),
        findingCount: findings.length,
        scannedFileCount: ctx.files.length,
      };
    },
  };
}

function buildPrTitle(bot: BotDefinition, findings: BotFinding[]): string {
  if (bot.config.outputFormat === "document") {
    return `docs(${bot.name}): generate documentation`;
  }
  return `fix(${bot.name}): resolve ${findings.length} issue${findings.length !== 1 ? "s" : ""}`;
}

function buildPrBody(bot: BotDefinition, findings: BotFinding[]): string {
  const lines = [`## ${bot.description}\n`];

  if (bot.config.outputFormat === "document") {
    lines.push(`Generated documentation using **${bot.name}** bot.\n`);
  } else {
    lines.push(`Found **${findings.length}** issue${findings.length !== 1 ? "s" : ""}:\n`);

    for (const f of findings) {
      const loc = f.line ? `:${f.line}` : "";
      lines.push(`- **${f.severity}** \`${f.file}${loc}\`: ${f.description}`);
    }
  }

  lines.push("\n---\n*Generated by [nanobots](https://nanobots.sh)*");
  return lines.join("\n");
}

/**
 * Convert an array of BotDefinitions into Nanobots.
 */
export function adaptAllToNanobots(bots: BotDefinition[]): Nanobot[] {
  return bots.map(adaptToNanobot);
}
